#!/usr/bin/env python3
"""
SMPC coordination server for a 3-party pairwise one-time-pad average.

Roles:
  - Party A, Party B, Party C: each runs in their own browser, enters one number,
    and submits only a *masked share* (input + pairwise masks) to this server.
  - Aggregator: a separate page that fetches the masked shares and computes the
    average. The aggregator never sees raw inputs or masks.

Protocol (pairwise OTP masking):
  For each pair (i, j) with i < j, a random 64-bit mask r_ij is generated by
  party i and delivered to party j through /api/mask.
  Each party computes its masked share locally:
      s_A = x_A + r_AB + r_AC
      s_B = x_B - r_AB + r_BC
      s_C = x_C - r_AC - r_BC
  Summing all three masked shares cancels every mask, yielding x_A + x_B + x_C.

All arithmetic is done in fixed-point (x * 1_000_000) so decimals work with
BigInt on the client.
"""

import http.server
import json
import os
import threading
from urllib.parse import urlparse, parse_qs

PORT = 8765
PUBLIC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "public")
PARTIES = ["A", "B", "C"]

state_lock = threading.Lock()
state = {
    "masks": {},    # "FROM->TO" -> decimal string (may be negative)
    "shares": {},   # "A"|"B"|"C" -> decimal string
}


def reset_state():
    with state_lock:
        state["masks"].clear()
        state["shares"].clear()


def public_state():
    with state_lock:
        return {
            "masks_relayed": sorted(state["masks"].keys()),
            "shares_submitted": sorted(state["shares"].keys()),
        }


def is_decimal_string(s):
    if not isinstance(s, str) or not s:
        return False
    return s.lstrip("-").isdigit() and not (s == "-" or s.startswith("--"))


class Handler(http.server.BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        return  # quiet

    # --- response helpers -------------------------------------------------
    def _send_json(self, code, payload):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _send_file(self, path, content_type="text/html; charset=utf-8"):
        try:
            with open(path, "rb") as f:
                body = f.read()
        except FileNotFoundError:
            self.send_error(404)
            return
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _read_json(self):
        length = int(self.headers.get("Content-Length", "0") or "0")
        if length <= 0:
            return {}
        raw = self.rfile.read(length)
        return json.loads(raw.decode("utf-8"))

    # --- GET --------------------------------------------------------------
    def do_GET(self):
        parsed = urlparse(self.path)
        path = parsed.path
        qs = parse_qs(parsed.query)

        # Static routes
        if path in ("/", "/index.html"):
            return self._send_file(os.path.join(PUBLIC_DIR, "home.html"))
        if path == "/aggregator":
            return self._send_file(os.path.join(PUBLIC_DIR, "aggregator.html"))
        parts = path.strip("/").split("/")
        if len(parts) == 2 and parts[0] == "party" and parts[1].upper() in PARTIES:
            return self._send_file(os.path.join(PUBLIC_DIR, "party.html"))

        # API routes
        if path == "/api/state":
            return self._send_json(200, public_state())

        if path == "/api/masks":
            recipient = (qs.get("for", [""])[0] or "").upper()
            if recipient not in PARTIES:
                return self._send_json(400, {"error": "invalid recipient"})
            with state_lock:
                incoming = [
                    {"from": key.split("->")[0], "value": val}
                    for key, val in state["masks"].items()
                    if key.split("->")[1] == recipient
                ]
            return self._send_json(200, {"masks": incoming})

        if path == "/api/result":
            with state_lock:
                submitted = sorted(state["shares"].keys())
                if len(submitted) < 3:
                    return self._send_json(200, {
                        "ready": False,
                        "shares_submitted": submitted,
                    })
                shares = {p: state["shares"][p] for p in PARTIES}
                total = sum(int(v) for v in shares.values())
            return self._send_json(200, {
                "ready": True,
                "shares": shares,
                "sum": str(total),
            })

        self.send_error(404)

    # --- POST -------------------------------------------------------------
    def do_POST(self):
        parsed = urlparse(self.path)
        path = parsed.path

        if path == "/api/reset":
            reset_state()
            return self._send_json(200, {"ok": True})

        if path == "/api/mask":
            try:
                body = self._read_json()
            except Exception:
                return self._send_json(400, {"error": "bad json"})
            frm = str(body.get("from", "")).upper()
            to = str(body.get("to", "")).upper()
            val = body.get("value", "")
            if frm not in PARTIES or to not in PARTIES or frm == to:
                return self._send_json(400, {"error": "invalid from/to"})
            if not is_decimal_string(val):
                return self._send_json(400, {"error": "value must be a decimal string"})
            with state_lock:
                state["masks"][f"{frm}->{to}"] = val
            return self._send_json(200, {"ok": True})

        if path == "/api/share":
            try:
                body = self._read_json()
            except Exception:
                return self._send_json(400, {"error": "bad json"})
            party = str(body.get("party", "")).upper()
            share = body.get("share", "")
            if party not in PARTIES:
                return self._send_json(400, {"error": "invalid party"})
            if not is_decimal_string(share):
                return self._send_json(400, {"error": "share must be a decimal string"})
            with state_lock:
                state["shares"][party] = share
            return self._send_json(200, {"ok": True})

        self.send_error(404)


def main():
    if not os.path.isdir(PUBLIC_DIR):
        raise SystemExit(f"Missing public dir: {PUBLIC_DIR}")
    httpd = http.server.ThreadingHTTPServer(("127.0.0.1", PORT), Handler)
    print(f"SMPC server running on http://127.0.0.1:{PORT}")
    print(f"  Home:       http://127.0.0.1:{PORT}/")
    print(f"  Party A:    http://127.0.0.1:{PORT}/party/a")
    print(f"  Party B:    http://127.0.0.1:{PORT}/party/b")
    print(f"  Party C:    http://127.0.0.1:{PORT}/party/c")
    print(f"  Aggregator: http://127.0.0.1:{PORT}/aggregator")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")


if __name__ == "__main__":
    main()
